version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: andesharvest-db
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: andesharvest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.0
    container_name: andesharvest-dbt
    working_dir: /usr/app
    volumes:
      - ./dbt_project:/usr/app
      # Descomenta si tienes config local:
      # - ./profiles.yml:/root/.dbt/profiles.yml
    depends_on:
      - postgres
    # CORRECCIÓN AQUÍ: Usamos 'entrypoint' para anular el comando 'dbt' por defecto
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
